### PR TITLE
fix: fix hz gen file permission

### LINKED ISSUE #1261: cmd tool hz init files with unexpected executable permissions
**Describe the bug**

hz 初始化项目后，除 build.sh 与 script/bootstrap.sh 外的文件也有可执行权限
After initializing a project, files other than "build.sh" and "script/bootstrap.sh" also have executable permissions.

**To Reproduce**

1. [ in shell ] hz new -module xxx/yyy
2. [ in shell ] ls -lah
3. See error

**Expected behavior**

只有 build.sh 与 script/bootstrap.sh 文件具有可执行权限
Only the files "build.sh" and "script/bootstrap.sh" have executable permissions.

**Hertz version:**
hz version v0.9.1
github.com/cloudwego/hertz v0.9.5

### PR DESCRIPTION
**Pull request by HeyJavaBean**
#### What type of PR is this?

fix

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) Translate the PR title into Chinese.
fix: 修复 hz 生成文件的权限

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional):

#### (Optional) The PR that updates user documentation:

fixes #1261

### CODE REVIEW

File: cmd/hz/generator/template.go [hunk 1]
```diff
@@ -247,7 +247,11 @@ func (tg *TemplateGenerator) Persist() error {
 		}
 
 		err = func() error {
-			file, err := os.OpenFile(abPath, os.O_CREATE|os.O_TRUNC|os.O_RDWR, os.FileMode(0o755))
+			fileMode := 0o644
+			if strings.HasSuffix(abPath, ".sh") {
+				fileMode = 0o755
+			}
+			file, err := os.OpenFile(abPath, os.O_CREATE|os.O_TRUNC|os.O_RDWR, os.FileMode(fileMode))
```
Comment (xiaost) [inline cmd/hz/generator/template.go:254]: 用os.WriteFile，原来的代码太长了。

Comment (HeyJavaBean) [reply cmd/hz/generator/template.go]: fixed

**Review by xiaost — APPROVED** [review]

**Review by FGYFFFF — APPROVED** [review]
