### PR TITLE
fix: WriteMultipartFormFile will fail when the Reader return EOF at first Read

### LINKED ISSUE #746: upload files EOF err when file size less than 512 bytes
**Describe the bug**

upload files EOF err when file size less than 512 bytes

**To Reproduce**

1. Go to pkg/protocol/multipart.go 139L 
2. It will return EOF err when file size less than 512B

**Expected behavior**

EOF should be ignored

**Screenshots**
76a41b39-588f-41c9-b597-083e6112fe7a

**Hertz version:**

v0.5.0

**Environment:**

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/byteide/.cache/go-build"
GOENV="/home/byteide/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/byteide/go/pkg/mod"
GONOPROXY="*.xxx.org,*.everphoto.cn,git.smartisan.com"
GONOSUMDB="*.xxx.org,*.everphoto.cn,git.smartisan.com"
GOOS="linux"
GOPATH="/home/byteide/go"
GOPRIVATE="*.byted.org,*.everphoto.cn,git.smartisan.com"
GOPROXY="https://go-mod-proxy.xxxx.org|https://goproxy.cn|https://proxy.golang.org|direct"
GOROOT="/home/byteide/go/go1.18.10"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/home/byteide/go/go1.18.10/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/byteide/workspace/xxx/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1286874491=/tmp/go-build -gno-record-gcc-switches"

**Additional context**

### PR DESCRIPTION
**Pull request by wzekin**
#### What type of PR is this?

fix
#### Check the PR title.

- [x] This PR title match the format: `<type>(optional scope): <description>`.
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io).

#### (Optional) Translate the PR title into Chinese.
修复：当传入的 `Reader` 的第一次 `Read` 返回 EOF 时，`WriteMultipartFormFile`将会失败

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: `WriteMultipartFormFile` does not check whether the return of Read is EOF. When Read returns EOF, `WriteMultipartForm` will return an error. Replace Read with `io.LimitedReader` to fix this
zh(optional): `WriteMultipartFormFile` 没有检查 Read 的返回是否是 EOF，当 Read 返回了 EOF 时， `WriteMultipartForm` 将会返回错误。将 Read 替换为 `io.LimitedReader` 来修复此问题

#### (Optional) Which issue(s) this PR fixes:

Fixes https://github.com/cloudwego/hertz/issues/746

### CODE REVIEW

File: pkg/protocol/multipart.go [hunk 1]
```diff
@@ -135,18 +136,22 @@ func MarshalMultipartForm(f *multipart.Form, boundary string) ([]byte, error) {
...
 func WriteMultipartFormFile(w *multipart.Writer, fieldName, fileName string, r io.Reader) error {
 	// Auto detect actual multipart content type
-	cbuf := make([]byte, 512)
-	size, err := r.Read(cbuf)
+	reader := &io.LimitedReader{
+		R: r,
+		N: 512,
+	}
+
+	data, err := ioutil.ReadAll(reader)
```
Comment (welkeyever) [inline pkg/protocol/multipart.go:144]: 可以直接处理一下EOF这个错误而不引入LimitedReader吗

Comment (wzekin) [reply pkg/protocol/multipart.go]: done，之前怕处理 EOF 会有一些遗留的问题，不过仔细看起来也还好，没啥问题

**Review by Duslia — APPROVED** [review]

**Review by welkeyever — APPROVED** [review]
LGTM

**Review by FGYFFFF — APPROVED** [review]

**Review by li-jin-gou — APPROVED** [review]
